### ISSUE TITLE
Can't scroll on Chrome - Windows

### ISSUE THREAD

**Issue by kosanr1** [stared/interactive-machine-learning-list#16]
I can't scroll because this fancy canvas is above page content. Change position:fixed on position:absolute. Or leave position: fixed and add pointer-events: none. 

https://scr.hu/Xw2MBB

**Comment by stared** [comment]
Thanks! I would really appreciate your Pull Request.

**Comment by stared** [comment]
`position: absolute;` breaks mouseover (it is shifted). `pointer-events: none;` works well.
