### ISSUE TITLE
Add style

### ISSUE THREAD

**Issue by stared** [stared/interactive-machine-learning-list#4]
Now it is so web 1.0. Adding style (ideally something more creative that Bootstrap) would make it nicer. 

Open for PRs.

**Comment by BrettGregson** [comment]
I'm happy to take this task on. Feel free to provide me with examples of what you have in mind

**Comment by stared** [comment]
@BrettGregson I am open to ideas (I can do CSS; I am way worse at designing a good layout). As I list, http://ndres.me/kaggle-past-solutions/ or maybe better - tiles https://d3-discovery.net/.

**Comment by BrettGregson** [comment]
Thanks @stared, I quite like the tile layout. I'll start scaffolding an example and we can take it from there

**Comment by stared** [comment]
@BrettGregson Looking forward to your contribution! :)
