### ISSUE TITLE
Porting Artificial Intelligence A Modern Approach

### ISSUE THREAD

**Issue by samuelgoto** [stared/interactive-machine-learning-list#7]
Might be worth checking out:

http://aimacode.github.io/aima-javascript/

And more specifically this year's work:

https://regalhotpocket.github.io/Aimacode/Chapter5/index.html
http://code.sgo.to/2018/03/05/explorables-design-patterns.html
http://code.sgo.to/2018/03/05/google-summer-of-code.html

**Comment by stared** [comment]
@samuelgoto  Thank you for these links (to writing of yours), but I am not sure what you mean. As far as I see, it is NOT an issue (a bug report or feature request).
